### ISSUE TITLE
Authentication interface: publicKey in DidDoc an Array but string in type

### ISSUE THREAD

**Issue by AdamJLemmon** [decentralized-identity/did-resolver#20]
We are using the hosted v1 uniresolver, and `ethr` did-method, a did we are resolving for example [here](https://uniresolver.io/1.0/identifiers/did:ethr:0xCC59d32d61A1E469818e8E489D3559dda4Fac32d).

We were aiming to use the types direct from this project but noticed that `Authentication.publicKey` is defined [here](https://github.com/decentralized-identity/did-resolver/blob/02bdaf1687151bb934b10093042e576ed54b229c/src/resolver.ts#L47) as just a single string but the uniresolver is returning an array of publicKey strings:
```
  "authentication" : [ {
    "type" : "Secp256k1SignatureAuthentication2018",
    "publicKey" : [ "did:ethr:0xCC59d32d61A1E469818e8E489D3559dda4Fac32d#owner" ]
  } ],
```

Can we update `Authentication.publicKey` to `string[]` ?

**Comment by mirceanis** [comment]
Thank you for reporting this.
We are aware of these differences. The reason they're not yet patched is that the DID document spec is still a moving target and we did not want to waste effort here before the time is right.

The issue you mention is a problem of ethr-did-resolver since this library is only the aggregator of DID methods and does not perform processing of DID documents.

**Comment by AdamJLemmon** [comment]
Thanks @mirceanis ! Agreed on the moving target :)  

Understood, let me see then if we can approach this from the `ethr-did-resolver` end perhaps.  I'll close this for now. Thanks.
