### ISSUE TITLE
Why owner instead of controller?

### ISSUE THREAD

**Issue by pensivej** [decentralized-identity/did-resolver#54]
Is there a specific reason why you call 'controller' property 'owner' in pubkey?
To follow w3c DID spec, I think we should change it to 'controller'

**Comment by mirceanis** [comment]
It is a legacy, not intentionally kept like that, and it should be updated.

This resolver was built before the W3C spec was a thing and was not updated for developer bandwidth reasons and because the controller/owner property of keys was not used in any project.

Feel free to submit a PR, especially if you are using this directly.
